name: Trigger Workflow in Repo steven-rhodes1

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Repository A
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.STEVEN_RHODES1_TOKEN}}
          script: |
            github.actions.createWorkflowDispatch({
              owner: 'steven-rhodes1',
              repo: 'sandbox',
              workflow_id: 'pull-request-workflow.yml',
              ref: 'main',
              inputs: {
                pr_number: 'PR is ${{ github.event.pull_request.number }}'
              }
            })
