name: Trigger Another Workflow
on: 
  pull_request:
    branches: [main]

jobs:
  code-scan:

    steps: 
    - name: Run Code Scan
      uses: aurelien-baudet/workflow-dispatch@v2.1.1
      with:
        workflow: pull-request-workflow.yaml
        repo: steven-rhodes1/sandbox
        ref: ${{ github.event.pull_request.head.ref }}
        wait-for-completion: true
        wait-for-completion-timeout: 5m
        wait-for-completion-interval: 30s
        display-workflow-run-url: true
        token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest