name: Trigger Another Workflow
on: 
  pull_request:
    branches: [main]

jobs:
  code-scan:
    name: Run Code Scan
    runs-on: ubuntu-latest
    steps:
    - name: Await Remote Job
      uses: Colby-Butler-Imprivata/await-remote-workflow@v1
      with:
        github-auth-token: ${{ secrets.MY_TOKEN }}
        token-type: 'Bearer'
        workflow-org: 'steven-rhodes1'
        workflow-repo: 'sandbox'
        workflow-yaml: 'pull-request-workflow.yml'
        workflow-branch: "main"
        workflow-inputs: '{\"release_string\": \"Pass In Whatever Values are Expected By The Workflow you Are Calling. Yes, you must escape quotes because this was written in BASH\"}'
        wait-timeout-in-minutes: '10'
